// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6wmlOVc8rA49jgfQOat7QiLdonyefjyg',
    appId: '1:475695758483:web:9c46fd839a16acc1c0a166',
    messagingSenderId: '475695758483',
    projectId: 'easy-chat-e88a9',
    authDomain: 'easy-chat-e88a9.firebaseapp.com',
    storageBucket: 'easy-chat-e88a9.firebasestorage.app',
    measurementId: 'G-5NHCJ0H4E9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAOZPdgsicAXULPS46FNyxc8rRz5s9wEY',
    appId: '1:475695758483:android:0249359269faad78c0a166',
    messagingSenderId: '475695758483',
    projectId: 'easy-chat-e88a9',
    storageBucket: 'easy-chat-e88a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEUpL4KX3nOK0gty3sv-Q1vjiKdV_aq8k',
    appId: '1:475695758483:ios:f3a43c4862890934c0a166',
    messagingSenderId: '475695758483',
    projectId: 'easy-chat-e88a9',
    storageBucket: 'easy-chat-e88a9.firebasestorage.app',
    iosClientId:
        '475695758483-esp6qi4ip5o8hefflc0ajc7nlg7m9j8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEUpL4KX3nOK0gty3sv-Q1vjiKdV_aq8k',
    appId: '1:475695758483:ios:f3a43c4862890934c0a166',
    messagingSenderId: '475695758483',
    projectId: 'easy-chat-e88a9',
    storageBucket: 'easy-chat-e88a9.firebasestorage.app',
    iosClientId:
        '475695758483-esp6qi4ip5o8hefflc0ajc7nlg7m9j8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6wmlOVc8rA49jgfQOat7QiLdonyefjyg',
    appId: '1:475695758483:web:083b14ffdbe4d1b8c0a166',
    messagingSenderId: '475695758483',
    projectId: 'easy-chat-e88a9',
    authDomain: 'easy-chat-e88a9.firebaseapp.com',
    storageBucket: 'easy-chat-e88a9.firebasestorage.app',
    measurementId: 'G-GJKBVYT6HD',
  );
}
